"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),os=require("node:os"),path=require("node:path"),fsp=require("node:fs/promises"),ib=require("../../src/runtime/interactionBus");
async function fx(t,limits){const root=await fsp.mkdtemp(path.join(os.tmpdir(),"damar-r1-"));t.after(()=>fsp.rm(root,{recursive:true,force:true}));const media=ib.createMediaSubsystem({storageRoot:root,limits});await media.ready;return{root,media}}
const item=(source,extra={})=>({source,fileName:"item.bin",declaredMimeType:"application/octet-stream",sourceChannel:"console",...extra});
function busFor(media,manager){const bus=ib.createInteractionBus({clock:()=>1000,idFactory:ib.createSequentialIdFactory(),mediaIngress:media});return{bus,ingress:ib.createManagerInteractionIngress({bus,manager,mediaSubsystem:media})}}

test("R1 production factory seals media authority substitution",()=>{assert.throws(()=>ib.createProductionBus({mediaIngress:{isCanonicalMediaReference:()=>true}}),/accepts no caller bindings/);assert.throws(()=>ib.createProductionManagerInteractionIngress({mediaIngress:{}}),/accepts no caller bindings/)});
test("R1 hostile external source rejects without traps",async t=>{const{media}=await fx(t);let calls=0;const source=new Proxy({}, {get(){calls++;throw Error("trap")},getPrototypeOf(){calls++;throw Error("trap")}});await assert.rejects(media.ingest(item(source)),e=>e.code==="MEDIA_UNSUPPORTED_SOURCE");assert.equal(calls,0)});
test("R1 size boundaries use actual bytes",async t=>{const{media}=await fx(t,{maxAttachmentBytes:4,maxChunkBytes:4});for(const n of [0,3,4])assert.equal((await media.ingest(item(Buffer.alloc(n),{fileName:`f${n}.bin`}))).sizeBytes,n);await assert.rejects(media.ingest(item(Buffer.alloc(5))),e=>e.code==="MEDIA_OVERSIZE")});
test("R1 trusted chunk is rejected against chunk budget",async t=>{const{media}=await fx(t,{maxAttachmentBytes:8,maxChunkBytes:4});async function* chunks(){yield Buffer.alloc(5)}await assert.rejects(media.ingest(item(media.createTrustedByteSource(chunks()))),e=>e.code==="MEDIA_OVERSIZE")});
test("R1 stalled trusted stream times out, cancels, and cleans staging",async t=>{const{root,media}=await fx(t,{idleTimeoutMs:20,overallTimeoutMs:40});let cancelled=0;const iterable={[Symbol.asyncIterator](){return{next:()=>new Promise(()=>{}),return:async()=>({done:true})}}};const source=media.createTrustedByteSource(iterable,()=>{cancelled++});await assert.rejects(media.ingest(item(source)),e=>e.code==="MEDIA_TIMEOUT");assert.equal(cancelled,1);assert.deepEqual(await fsp.readdir(path.join(root,"staging")),[])});
test("R1 aggregate rejection is transactional and preserves preexisting dedup",async t=>{const{root,media}=await fx(t,{maxAttachmentBytes:6,maxAggregateBytes:6});const existing=await media.ingest(item(Buffer.from("same")));const before=await fsp.readdir(path.join(root,"objects"));await assert.rejects(media.ingestMany([item(Buffer.from("same"),{fileName:"a.bin"}),item(Buffer.from("xyz"),{fileName:"b.bin"})]),e=>e.code==="MEDIA_AGGREGATE_EXCEEDED");assert.deepEqual(await fsp.readdir(path.join(root,"objects")),before);assert.deepEqual(await fsp.readdir(path.join(root,"staging")),[]);assert.deepEqual((await media.resolver.resolveDurable(existing.mediaId)).bytes,Buffer.from("same"))});
test("R1 durable catalog survives restart without descriptor rehydration",async t=>{const{root,media:a}=await fx(t);const ref=await a.ingest(item(Buffer.from("restart")));const b=ib.createMediaSubsystem({storageRoot:root});await b.ready;assert.deepEqual((await b.resolver.resolveDurable(ref.mediaId)).bytes,Buffer.from("restart"));assert.equal(b.isCanonicalMediaReference(ref),false);assert.equal(b.isCanonicalMediaReference({...ref}),false)});
test("R1 read verifies truncate, extend, replace, and same-size mutation",async t=>{for(const [name,bytes] of [["truncate",Buffer.from("x")],["extend",Buffer.from("tampered-more")],["replace",Buffer.from("12345678")],["mutate",Buffer.from("XXXXXXXX")]]){const{root,media}=await fx(t);const ref=await media.ingest(item(Buffer.from("original"),{fileName:`${name}.bin`}));await fsp.writeFile(path.join(root,"objects",`${ref.sha256}.blob`),bytes);await assert.rejects(media.resolver.resolveDurable(ref.mediaId),e=>e.code==="MEDIA_INTEGRITY_FAILURE")}});
test("R1 dedup target corruption fails closed without overwrite",async t=>{const{root,media}=await fx(t);const ref=await media.ingest(item(Buffer.from("same")));await fsp.writeFile(path.join(root,"objects",`${ref.sha256}.blob`),Buffer.from("evil"));await assert.rejects(media.ingest(item(Buffer.from("same"),{fileName:"again.bin"})),e=>e.code==="MEDIA_INTEGRITY_FAILURE")});
test("R1 interaction binding resolves exact admitted bytes, descriptor alone cannot",async t=>{const{media}=await fx(t),calls=[],manager={async handle(x){calls.push(x);return{managerRequestId:"r",outcome:"COMPLETED",lifecycleState:"COMPLETED",detail:"ok"}}},{ingress}=busFor(media,manager);const result=await ingress.ingestAttachments("console",{text:"media",userId:"u"},[item(Buffer.from("bound"),{fileName:"bound.bin"})]);await new Promise(r=>setImmediate(r));assert.equal(result.accepted,true);const got=await media.resolver.resolveInteraction(result.interactionId,result.attachmentIds[0]);assert.deepEqual(got.bytes,Buffer.from("bound"));assert.equal(Object.isFrozen(calls[0].payload.attachments[0]),true);await assert.rejects(media.resolver.resolveInteraction("ix_forged",result.attachmentIds[0]),e=>e.code==="MEDIA_FOREIGN_REFERENCE")});
test("R1 all five channels share one ingress and Manager handoff",async t=>{const{media}=await fx(t),calls=[],manager={async handle(x){calls.push(x);return{managerRequestId:"r",outcome:"COMPLETED",lifecycleState:"COMPLETED",detail:"ok"}}},{ingress}=busFor(media,manager);for(const channel of ingress.channels){const r=await ingress.ingestAttachments(channel,{text:`file-${channel}`,userId:channel},[item(Buffer.from(channel),{fileName:`${channel}.bin`,sourceChannel:channel})]);assert.equal(r.accepted,true);assert.deepEqual((await media.resolver.resolveInteraction(r.interactionId,r.attachmentIds[0])).bytes,Buffer.from(channel))}await new Promise(r=>setImmediate(r));assert.equal(calls.length,5);assert.deepEqual(calls.map(x=>x.channelType),ingress.channels)});
test("R1 sealed production ingress carries media on all five channels",async t=>{const root=await fsp.mkdtemp(path.join(os.tmpdir(),"damar-production-r1-"));t.after(()=>fsp.rm(root,{recursive:true,force:true}));const original=os.homedir;os.homedir=()=>root;t.after(()=>{os.homedir=original});const ingress=ib.createProductionManagerInteractionIngress();for(const channel of ingress.channels){const r=await ingress.ingestAttachments(channel,{text:`production-${channel}`,userId:channel},[item(Buffer.from(channel),{fileName:`${channel}.bin`,sourceChannel:channel})]);assert.equal(r.accepted,true);assert.deepEqual((await ingress.mediaResolver.resolveInteraction(r.interactionId,r.attachmentIds[0])).bytes,Buffer.from(channel))}});
test("R1 provenance forgery matrix fails",async t=>{const{media}=await fx(t),ref=await media.ingest(item(Buffer.from("x"))),foreign=(await fx(t)).media;const fake={...ref,trusted:true,verified:true,authorized:true};for(const x of [fake,{...ref},JSON.parse(JSON.stringify(ref)),Object.create(ref),new Proxy(ref,{})])assert.equal(media.isCanonicalMediaReference(x),false);assert.equal(media.isCanonicalMediaReference(await foreign.ingest(item(Buffer.from("x")))),false)});
test("R1 suspicious ADS and drive-relative display names reject",async t=>{const{media}=await fx(t);for(const fileName of ["file.txt:stream","colon:name","C:evil"])await assert.rejects(media.ingest(item(Buffer.from("x"),{fileName})),e=>e.code==="MEDIA_INVALID_FILENAME")});
test("R1 MIME confidence is evidence, not validation",async t=>{const{media}=await fx(t);assert.equal((await media.ingest(item(Buffer.from("89504e470d0a1a0a", "hex"),{fileName:"x.png"}))).detectionConfidence,"weak-signature");assert.equal((await media.ingest(item(Buffer.from("plain"),{fileName:"x.txt"}))).detectionConfidence,"text-heuristic");assert.equal((await media.ingest(item(Buffer.from([0]),{fileName:"x.bin"}))).detectionConfidence,"unknown")});
test("R1 startup scavenges only stale generated staging files",async t=>{const root=await fsp.mkdtemp(path.join(os.tmpdir(),"damar-scavenge-"));t.after(()=>fsp.rm(root,{recursive:true,force:true}));await fsp.mkdir(path.join(root,"staging"),{recursive:true});await fsp.mkdir(path.join(root,"objects"));await fsp.mkdir(path.join(root,"catalog"));const stale=path.join(root,"staging","stage_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.partial"),keep=path.join(root,"staging","foreign.tmp");await fsp.writeFile(stale,"x");await fsp.writeFile(keep,"x");await fsp.utimes(stale,new Date(0),new Date(0));const media=ib.createMediaSubsystem({storageRoot:root,limits:{stagingMaxAgeMs:1}});await media.ready;assert.equal(await fsp.stat(stale).then(()=>true,()=>false),false);assert.equal(await fsp.stat(keep).then(()=>true,()=>false),true)});
test("R1 Windows junction replacement fails closed",{skip:process.platform!=="win32"},async t=>{const{root,media}=await fx(t),outside=await fsp.mkdtemp(path.join(os.tmpdir(),"damar-outside-"));t.after(()=>fsp.rm(outside,{recursive:true,force:true}));await fsp.rmdir(path.join(root,"objects"));await fsp.symlink(outside,path.join(root,"objects"),"junction");await assert.rejects(media.ingest(item(Buffer.from("escape"))),e=>e.code==="MEDIA_STORAGE_ESCAPE");assert.deepEqual(await fsp.readdir(outside),[])});
